### ISSUE TITLE
serde 0.9 branch doesn't serialize Option correctly

### ISSUE THREAD

**Issue by Pratyush** [jrasky/corepack#5]
I believe there's a bug with serializing `Option` types on the `serde` 0.9 branch. Below is a minimal example that should trigger this:

```
extern crate corepack;
extern crate serde;

fn main() {
    let node = Some(7);
    let encoded = corepack::to_bytes(node).unwrap();
    let value: Result<Option<u64>, corepack::error::Error> = corepack::from_bytes(&encoded);
    println!("value: {:?}", value);
}
```

EDIT: minimized example further.

**Comment by jrasky** [comment]
Thanks for pointing that out, I'll try to fix it this weekend and then merge the serde 0.9 branch + bump the crates.io version. There are probably other issues, I'll fix them as they come up.

**Comment by Pratyush** [comment]
Cool, thanks for the quick response :)

**Comment by jrasky** [comment]
I was busy this weekend, but I should have some free time at some point this week.

**Comment by jrasky** [comment]
I've figured out the issue. When I serialize an Option, I just serialize its value directly, or NIL if the option is None. The problem is that OptionVisitor expects the deserializer to call visit_some before the actual value in the Option. The code as it is right now just visits the value directly, which is where the error comes from.

I'm thinking about a solution, whether it be some extra infrastructure around how Deserializer handles deserialize_option, or something around how Serializer encodes it.

**Comment by dtolnay** [comment]
I don't think the Serializer would need to change. The Deserializer should implement deserialize_option so that it calls visit_some or visit_none depending on whether there is a value. For example [here is the one from serde_json](https://github.com/serde-rs/json/blob/v0.9.10/json/src/de.rs#L599-L612).

**Comment by jrasky** [comment]
I think I'm going to take the path that serde_json takes, and add a peek closure to Deserialize.

**Comment by jrasky** [comment]
Okay, I think I fixed it
